package com.example.backend.job.domain;

public enum RoleFamily {
    BACKEND, FRONTEND, FULL_STACK, SOFTWARE_ENGINEERING, DEVOPS_PLATFORM,
    DATA_ENGINEERING, DATA_SCIENCE, DATA_ANALYTICS, ML_AI, SECURITY, UNKNOWN
}
